### ISSUE TITLE
RF-07  CRUD de Productos

### ISSUE THREAD

**Issue by w4xccino** [w4xccino/peepo-app#12]
## Descripción
El sistema le permitirá al administrador realizar la gestión de producto otorgándole el permiso de hacer la acción CRUD crear, actualizar, insertar y eliminar sobre dicho producto.

## Tasks
- [ ] Conexión a la Base De Datos.
- [ ] Listado de Productos.
- [ ] Creción de Productos.
- [ ] Actualización de detalles de productos.
- [ ] Eliminación de Productos.

## Anormalidades
Cuando el administrador actualice los productos en la base de datos., el usuario podrá visualizar las nuevas actualizaciones de cada producto. 

## Aceptación
Este requerimiento es indispensable para la aplicación, ya que cuenta con todo el contenido que se necesita.
