### ISSUE TITLE
RF-02 Autenticación De Usuarios

### ISSUE THREAD

**Issue by w4xccino** [w4xccino/peepo-app#8]
## Descripción
Deacuerdo al requerimiento **RF-03** establece que el usuario podrá guardar sus datos para poder autenticarse y que El actor debe ser capaz de ingresar a la aplicación por medio de un nombre de usuario y contraseña. 

## PreCondición
- [x] El usuario debe estar previamente registrado en el sistema.

## Tasks
- [x] Conexión a la base de datos.
- [ ] Cifrado en el logeo de usuario. 

## Anormalidades
Si el nombre de usuario es incorrecto, se le permitirá al usuario crear una nueva cuenta o tener un máximo de 3 intentos para poder iniciar sesión, en caso contrario, no podrá seguir haciendo más intentos durante el periodo de una hora.
